version: '3'
services:
  rabbit1:
    image: rabbitmq:3.7.7-management
    hostname: rabbit1
    container_name: rabbit1
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    labels:
      NAME: rabbitmq